from gym_ur5_gripper.envs.ur5_gripper_env import UR5GripperEnv
# from gym_ur5_gripper.envs.ur5_gripper.ur5_gripper_catch_ball import UR5GripperCatchBallEnv
from gym_ur5_gripper.envs.hdt_arm_env import HDTArmEnv
from gym_ur5_gripper.envs.hdt_arm.pick_and_place import HDTArmPickAndPlaceEnv